# Generated by Django 4.2.6 on 2023-10-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_record_pix'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='side',
            field=models.CharField(choices=[('D', 'D'), ('E', 'E')], default='D', max_length=1),
        ),
    ]
