# Generated by Django 4.2.6 on 2023-10-16 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='max_players',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Doubles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_doubles', to='website.record')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_doubles', to='website.record')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='doubles',
            field=models.ManyToManyField(blank=True, to='website.doubles'),
        ),
    ]
