# Generated by Django 4.2.6 on 2023-10-19 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_tournament_max_players_doubles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('result_a', models.PositiveIntegerField(blank=True, null=True)),
                ('result_b', models.PositiveIntegerField(blank=True, null=True)),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a_matches', to='website.doubles')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b_matches', to='website.doubles')),
            ],
        ),
    ]
