# Generated by Django 4.2.6 on 2023-11-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_match_result_a_alter_match_result_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubles',
            name='balance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
