# Generated by Django 4.2.6 on 2023-11-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_doubles_balance_alter_doubles_conc_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubles',
            name='balance',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
